2024-08-21 19:06:45,828 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1055, "Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fastapi.product_table.product_subcategory_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.product_category_id AS product_table_product_category_id, count(product_table.product_subcategory_id) AS count_2, product_table.product_subcategory_id AS product_table_product_subcategory_id 
FROM product_table GROUP BY product_table.product_category_id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-21 19:10:09,480 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fastapi.product_table.product_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.product_id AS product_table_product_id, product_table.product_name AS product_table_product_name, product_table.product_description AS product_table_product_description, product_table.product_price AS product_table_product_price, product_table.product_quantity AS product_table_product_quantity, product_table.product_image_name AS product_table_product_image_name, product_table.product_image_path AS product_table_product_image_path, product_table.created_date AS product_table_created_date, product_table.created_by AS product_table_created_by, product_table.edited_date AS product_table_edited_date, product_table.edited_by AS product_table_edited_by, product_table.is_deleted AS product_table_is_deleted, product_table.product_category_id AS product_table_product_category_id, product_table.product_subcategory_id AS product_table_product_subcategory_id, count(product_table.product_subcategory_id) AS count_2, product_table.product_id AS product_table_product_id__1, product_table.product_name AS product_table_product_name__1, product_table.product_description AS product_table_product_description__1, product_table.product_price AS product_table_product_price__1, product_table.product_quantity AS product_table_product_quantity__1, product_table.product_image_name AS product_table_product_image_name__1, product_table.product_image_path AS product_table_product_image_path__1, product_table.created_date AS product_table_created_date__1, product_table.created_by AS product_table_created_by__1, product_table.edited_date AS product_table_edited_date__1, product_table.edited_by AS product_table_edited_by__1, product_table.is_deleted AS product_table_is_deleted__1, product_table.product_category_id AS product_table_product_category_id__1, product_table.product_subcategory_id AS product_table_product_subcategory_id__1 
FROM product_table GROUP BY product_table.product_category_id, product_table.product_subcategory_id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-21 19:10:35,474 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'list' object has no attribute 'asc'
2024-08-21 19:12:16,523 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1140, "In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'fastapi.product_table.product_category_id'; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.product_category_id AS product_table_product_category_id 
FROM product_table]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-21 19:14:09,155 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fastapi.product_table.product_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.product_id AS product_table_product_id, product_table.product_name AS product_table_product_name, product_table.product_description AS product_table_product_description, product_table.product_price AS product_table_product_price, product_table.product_quantity AS product_table_product_quantity, product_table.product_image_name AS product_table_product_image_name, product_table.product_image_path AS product_table_product_image_path, product_table.created_date AS product_table_created_date, product_table.created_by AS product_table_created_by, product_table.edited_date AS product_table_edited_date, product_table.edited_by AS product_table_edited_by, product_table.is_deleted AS product_table_is_deleted, product_table.product_category_id AS product_table_product_category_id, product_table.product_subcategory_id AS product_table_product_subcategory_id 
FROM product_table GROUP BY product_table.product_category_id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-21 19:15:09,721 - backend.services.product_services - ERROR - Product Read Services Exception: 500: Neither 'count' object nor 'Comparator' object has an attribute 'group_by'
2024-08-21 19:20:45,862 - backend.services.product_services - ERROR - Product Read Services Exception: 500: Neither 'count' object nor 'Comparator' object has an attribute 'group_by'
2024-08-21 19:25:49,413 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fastapi.product_table.is_deleted' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.is_deleted AS product_table_is_deleted 
FROM product_table GROUP BY product_table.product_category_id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-21 19:26:16,546 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fastapi.product_table.product_category_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.product_category_id AS product_table_product_category_id 
FROM product_table GROUP BY product_table.is_deleted]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-22 15:45:50,653 - backend.services.product_services - ERROR - Product Read Services Exception: 400: dictionary update sequence element #0 has length 4; 2 is required
2024-08-22 15:54:04,097 - backend.services.product_services - ERROR - Product Read Services Exception: 500: count.__init__() takes from 1 to 2 positional arguments but 3 were given
2024-08-22 15:54:41,343 - backend.services.product_services - ERROR - Product Read Services Exception: 500: count.__init__() takes from 1 to 2 positional arguments but 3 were given
2024-08-22 15:54:45,297 - backend.services.product_services - ERROR - Product Read Services Exception: 500: count.__init__() takes from 1 to 2 positional arguments but 3 were given
2024-08-22 15:57:37,977 - backend.services.product_services - ERROR - Product Read Services Exception: 500: count.__init__() takes from 1 to 2 positional arguments but 3 were given
2024-08-22 16:01:07,071 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fastapi.product_table.product_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.product_id AS product_table_product_id 
FROM product_table GROUP BY product_table.product_category_id, product_table.product_subcategory_id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-22 16:04:21,835 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1055, "Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'fastapi.product_table.product_subcategory_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT count(product_table.product_category_id) AS count_1, product_table.product_category_id AS product_table_product_category_id, count(product_table.product_subcategory_id) AS count_2, product_table.product_subcategory_id AS product_table_product_subcategory_id 
FROM product_table GROUP BY product_table.product_category_id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-22 16:12:01,562 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'list' object has no attribute 'query'
2024-08-22 16:12:10,362 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Query' object has no attribute 'query'
2024-08-22 16:12:55,778 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Query' object has no attribute 'query'
2024-08-22 16:14:25,479 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Query' object is not callable
2024-08-22 16:35:44,410 - backend.services.product_services - ERROR - Product Read Services Exception: 500: list assignment index out of range
2024-08-23 11:52:55,282 - backend.services.product_services - ERROR - Product Read Services Exception: 500: name 'category_table' is not defined
2024-08-23 11:55:06,697 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 11:55:53,351 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 11:57:43,980 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:02:08,691 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:02:46,659 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:03:18,148 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:03:54,422 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:10:21,802 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:12:23,206 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:12:54,951 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_name'
2024-08-23 12:13:24,701 - backend.services.product_services - ERROR - Product Read Services Exception: 500: 'Table' object has no attribute 'category_id'
2024-08-23 12:30:24,241 - backend.services.product_services - ERROR - Product Read Services Exception: 500: name 'parent_category_table' is not defined
2024-08-23 12:30:36,370 - backend.services.product_services - ERROR - Product Read Services Exception: 500: (pymysql.err.OperationalError) (1066, "Not unique table/alias: 'category_table'")
[SQL: SELECT product_table.product_id AS product_table_product_id, product_table.product_name AS product_table_product_name, category_table.category_name AS product_category_name, subcategory_table.subcategory_name AS subcategory_table_subcategory_name, category_table.category_name AS subcategory_category_name 
FROM product_table INNER JOIN category_table ON category_table.category_id = product_table.product_category_id INNER JOIN subcategory_table ON subcategory_table.subcategory_id = product_table.product_subcategory_id INNER JOIN category_table ON category_table.category_id = subcategory_table.subcategory_category_id]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-08-23 13:41:20,149 - backend.services.product_services - ERROR - Product Read Services Exception: 500: product_count
2024-08-23 13:55:20,888 - backend.services.product_services - ERROR - Product Read Services Exception: 500: subcategory_quantity
2024-08-23 13:55:36,087 - backend.services.product_services - ERROR - Product Read Services Exception: 500: subcategory_quantity
